### ISSUE TITLE
Site Information issues

### ISSUE THREAD

**Issue by omarbenites** [AGROFIMS/hagrofims#195]
Here we will place al the issues related to Sites and Geodatabase. 
I also upload the GADM database in csv version.

GeoDataBase GADM  [gadm36_table.zip](https://github.com/AGROFIMS/hagrofims/files/2984654/gadm36_table.zip)

**Comment by omarbenites** [comment]
- [x] #25 site - should be able to see all sites when logged in 
- [ ] #34  Batch addition of sites 
- [ ] #40 Site longitud and latitude should change when ....
